---
title: "Proyecto"
author: "Santiago Fernández Sáenz y Erick Venegas Espinoza"
date: "`r Sys.Date()`"
output: html_document
---

# Preparación inicial

## Librerías

Se inicia cargando las librerías necesarias para el desarrollo del trabajo.

```{r librerias}
pacman::p_load(dplyr,
               ggplot2,
               janitor,
               readr,
               skimr)
```

## Datos

Se cargan los datos necesarios.

```{r carga_datos}
datos <- read_delim(
  "data/Motor vehicle insurance data.csv",
  delim = ";",
  escape_double = FALSE,
  trim_ws = TRUE
)
```

Ahora se limpia el nombre de los datos.

```{r nombres_datos}
datos <- clean_names(datos)
```

Se ajusta el formato de las fechas.

```{r formato_fechas}
# Fecha de inicio del contrato
datos <- datos %>%
  mutate(date_start_contract = as.Date(date_start_contract, format = "%d/%m/%Y"))

# Fecha de la última renovación del contrato
datos <- datos %>%
  mutate(date_last_renewal = as.Date(date_last_renewal, format = "%d/%m/%Y"))

# Fecha de la próxima renovación del contrato
datos <- datos %>%
  mutate(date_next_renewal = as.Date(date_next_renewal, format = "%d/%m/%Y"))

# Fecha de nacimiento
datos <- datos %>%
  mutate(date_birth = as.Date(date_birth, format = "%d/%m/%Y"))

# Fecha de emisión de la licencia
datos <- datos %>%
  mutate(date_driving_licence = as.Date(date_driving_licence, format = "%d/%m/%Y"))

# Fecha de cancelación de la póliza, en caso de ocurrir
datos <- datos %>%
  mutate(date_lapse = as.Date(date_lapse, format = "%d/%m/%Y"))
```

